<!-- <link href="../../../resources/custom/print_format.css" media="print" rel="stylesheet" /> -->
<style type="text/css">
  @page {
    size:letter;
    margin-top: 0.7in; 
    margin-left: 0.7in;
    margin-right: 0.7in;
    margin-bottom: 0.7in;
   
  }
  hr {
     border: none; 
     border-bottom: 1px solid black;
  }
  table {
    border-collapse: collapse;
  }

  table, th, td {
    border: 1px solid black;
  }

</style>


<div style="display: none">
  <div id="demo" class="panel-body" style="color: black">
     <!-- begin panel-body -->
     <!--For Details-->
     
     <!--For Details-->
     <div class="panel" style="font-family: arial;">
        <p style="font-size: 14px; text-align: center">
           Republic of the Philippines<br>
           Province of Batangas<br>
           Municipality of Tuy<br>
        </p>
        <p style="font-size: 16px; font-weight:bold; text-align: center; margin-top: 20px; margin-bottom: 40px">OFFICE OF THE DEPUTIZED ZONING ADMINISTRATOR</p>
        <table>
          <tr>
            <td style="width: 480px;border-color: white">
              Date Created: <?php echo date('F,d Y')?>
            </td>
            <td style="width: 380px; text-align: right;border-color: white">
              Report No: ALR<?php echo date('Ymd')?>
            </td>
          </tr>
        </table>
        <hr>
        <p style="font-size: 19px; font-weight:bold; text-align: center; margin-top: 20px">APPLICANT LIST REPORT</p>
        <hr>

        <p style="font-size: 16px; text-align: justify">
          <b>Report Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           This report contains the details of applicants registered in the system.
           <br>
           &nbsp;&nbsp;&nbsp;
           Details in this report may be filtered according to the specifications and preferences set by the report generator.
        </p>
         <p style="font-size: 16px; text-align: justify">
          <b>Table Description:</b><br><br>
           &nbsp;&nbsp;&nbsp;
           The table contains the following fields:  applicant's name, home address, contact number, and their date of registration, respectively.
           <br>
        </p>
        <table>
            <thead>
                <tr>
                   <th>Name</th>
                   <th>Home Address</th>
                   <th>Contact No.</th>   
                   <th>Date Registered</th>
                </tr>
            </thead>
            <tbody>
                <?php include("report_applicants_filter_details.php");?>
            </tbody>
        </table>
        <hr>
        <br>
        <p style="font-size: 15px; margin-top:30px; margin-bottom: 15px">
          Report Generated By:<br><br><br>
          <b><?php echo $rev_compname; ?></b><br>
          <i><?php echo $up_pos;?></i>
        </p>
     </div>
     <!-- end panel-body -->
  </div>
</div>